### ISSUE TITLE
Bounty Payout Page

### ISSUE THREAD

**Issue by leviyehonatan** [hats-finance/hats#120]
### Motivation
After a hacker submits a claim that he has found a vurnability, he submits it and creates a transaction with his proof, after negotiating with the committee, the committee decides to pay the hacker, selecting the severity level they have decided on. This form allows to see the vurnability, create a proposal and sign it to allow a multi-sig signature of the contract action in a centralized way.

the page should be accessed by a committee member  after a bug is reported using a link sent on telegram to view its contents and create a payout proposal and execute it with a multi-sig conducted with the other members

## Used Mechanisms
- react-dom-router should be updated with a route to include the descriptionHash to be payed out
- subgraph should be used to retrieve the specific description hash to extract the beneficiary, submittedClaims->claimer is the beneficiary
- [vault-service](https://github.com/hats-finance/vault-editor-service) should add api calls as described below to allow the centralized signing process
- pgp keys vault should be used to make sure the pgp keys are visible after unlocking and for decrypting the message
- the actual encrypted message should be fetched from ipfs in order to decrypt it and show to the user
- the list of vaults should be used and filtered by the existing keys in the pgp keys vault after unlocking it
- after a successful decryption the contents of the ipfs should be decrypted using openpgp

## Description
when the page opens it is need to  use the subgraph to find the Claim event with that description hash and initialize the beneficiary address to what is specified in the event.

the user selects a vault, but the vaults list should be filtered to show only vaults to which the user has the private/public key as the vault, we could also try to decrypt with each one of the keys available one by one and the one that works would be the selected vault.

the descriptionHash is actually an IPFS hash which contains the contents of the description of the hash but it is encrypted using one of the key/s(can be one or more)
the user is being displayed with the list of vaults for which he has the keys for in his local storage vault(we can only know that after he unlocks the vault) and then there should be an attempt to decode the contents of the ipfs which is then displayed as the description of the claim.

the reward amount can be displayed using calcClaimRewards which returns a data structure described in the contracts, probably hackerReward should be used, @jellegerbrandy @shayzluf ?

when the vault is selected(automatically by a successful decryption) we can then retrieve the owners of a safe using gnosis safe api because we know the multi-sig address for that vault and we can check that the currently connected wallet is a member of that multisig wallet using gnosis-safe api of safe owner. if the connected wallet is not a member a message should be shown

after the user chooses the severity and edits beneficiary, and is satisfied he can create a proposal that can be signed by him and other members of the multi sig.

the contract call that should be used is pendingApprovalClaim which receives pid(vault id), beneficialy, and severity, all existing in the form. a server side api calls should be added on the vault-service to add a proposal for that description hash:   
PUT vault-service/claimproposal/:descriptionHash - add a proposal - in the body the proposal object 
GET vault-service/claimproposals/:descriptionHash - list all proposal id's that were submitted, 
GET vault-service/claimproposal/:descriptionHash/:proposalId - return the contents of the proposal and all its signatures in an object {proposal: the contract to be signed details, signatures: [] array of signatures added}.

the reviewer from the committee decides to create a proposal for the rest of the committee members to sign so he presses the create proposal button and 
once the transaction is decided we can sign it, and we collect the signatures at the server,
in order to create the signature we must use a signer to sign a transaction without actually calling the transaction, the details are not sure yet of how to do this, still investigating. a random/fixed signature can be used for now

so actually the address used to sign should not be stored as it can be recovered using verifyMessage which receives the original message(the transaction) and the signature, it returns the address. so this should be returned for any signature returned from vault-service/claimproposal/:descriptionHash/:proposalId while highlighting the signature if it belongs to the current user

the server cannot really verify that the signatures belong to addresses that are in the multi-sig because it cannot verify to which vault it is related to, as it has no private keys in it

the number of required signatures needed for this vault can be extracted from the gnosis safe api https://safe-transaction.rinkeby.gnosis.io/ using /safes/{address}/ and there you get the list of owners, and threshold which is the amount of minimal signatures needed to execute the transaction. also the nonce is available there and is needed for actually calling the transaction so no replay can occur. 

so the user interface should handle: 
* getting addresses for each signature using verifySignature from the returned signatures of the server
* signing and sending the signature to the server and re-getting the signatures afterwards
* highlighting the current wallet's address if it is in the list
* sign button that requests the signature from the wallet and when generated, should be sent to the service using the method described above.
* execute button that sends the transaction using all the collected signatures

https://medium.com/gauntlet-networks/multisig-transactions-with-gnosis-safe-f5dbe67c1c2d

## Action Items
- [x] get query param using useParams of react-dom-router 
- [x] graphql request for findDescriptionHash() requests all descriptionHashes equal to query params - https://thegraph.com/hosted-service/subgraph/hats-finance/hats_rinkeby_v4
- [x] show beneficiary - found with description hash on the event
- [x] select severity
- [x] show reward from contract
- [ ] create raw tranasaction for signing
- [ ] sign raw transaction  https://gist.github.com/rmeissner/0fa5719dc6b306ba84ee34bebddc860b
- [ ] encrypt raw transaction using owned vault key
- [ ] create new proposal button
- [ ] sign proposal button
- [ ] try to decode with openpgp, use each of the decryption keys (private keys) that are in the vault, after unlocking it.
- [ ] show message if non of the keys work
- [ ] payout - when enough signatures, send the signed tx to the server
- [ ] server send tx during the next safe period

**Comment by mwogates** [comment]
I added create and sign button, but hided sign button for now, need to add click functions for these buttons.

**Comment by leviyehonatan** [comment]
@DeerstalkerHats please create a separate ui ux issue and remove the tag from this one and link them from here
