### ISSUE TITLE
Vault Editor Improvements

### ISSUE THREAD

**Issue by leviyehonatan** [hats-finance/hats#128]
Seperate Issues for the following subjects should be added:
* bulk adding contracts
* after saving - show share modal with link copy button
* clarify pgp key workflow to user - show if user owns one of the keys after unlocking vault
* maybe use one id for all ipfs versions as initially planned, handle the list of historical ipfs versions on vault-editor-service
* when pressing save, if vault is unlocked then a warning should be shown to user that its impossible to check if his pgp key is added, if its unlocked, we verify if its added, if its not we show a message that he should add it if he wants to be able to read submissions sent to this vault
* while editing, a snapshot of the current edit should be saved to local storage according to the curretnly edited ipfs, or if a new edit, then for the new edit

**Comment by DeerstalkerHats** [comment]
Add severity name edit fields
