### ISSUE TITLE
Submit vulnerability-  Review text submission

### ISSUE THREAD

**Issue by DeerstalkerHats** [hats-finance/hats#159]
Need:
Added explanation to the submit flow - users didn't understand it is on-chain

**new text**
`By submitting the vulnerability, you encrypt the vulnerability description with the project PGP key. The hash of the encrypted description sends a transaction on-chain while sending the encrypted message to the committee group bot. The on-chain submission provides you avalanche for your submission.`

**Comment by leviyehonatan** [comment]
@shayzluf please review the text
