### ISSUE TITLE
UX / UI Committee tools- committee functions

### ISSUE THREAD

**Issue by shayzluf** [hats-finance/hats#233]
Add  the following 
User - Committee:
    1.Check-in-  once
         Add Pid - choose the vault from- if the user is connects with the right - add in the vault editor- or main page- or link to the 
         committee member (via what)
    2.Set committee

**Comment by DeerstalkerHats** [comment]
Added features 
1. See past 
2. You received a new msg -if you are part of a committee allow hats send you notifications- on web notification and browser tab

**Comment by DeerstalkerHats** [comment]
Dispute resolution- check with kleros the flow of their feature
