### ISSUE TITLE
Airdrop Machine landing page and flow dev

### ISSUE THREAD

**Issue by shayzluf** [hats-finance/hats#234]
```
{
  "wallets": [
    {
      "id": "0x1861eF2F60f952C7EFb107F2D277F761C7387cE3",
      "token_eligibility": {
        "committee_member": "200",
        "depositor": "200",
        "crow": "300",
        "coder": "1800",
        "early_contributor": "1000"
      },
      "nft_elegebility": [
        {
          "contract_address": "0x571f39d351513146248AcafA9D0509319A327C4D",
          "version": 2,
          "pid": 3,
          "tier": 0
        }
      ]
    }
  ]
}
```

**Comment by DeerstalkerHats** [comment]
See the design on Figma https://www.figma.com/file/XkYFhYf9eVDlaX6oL3COf2/Hats-hand-over?node-id=1244%3A2584

![Image](https://user-images.githubusercontent.com/87365901/177107206-9d85eb37-06ca-44f7-a5fc-b91f29793127.png)


![Image](https://user-images.githubusercontent.com/87365901/177107325-31e6cc86-bf56-4ab1-ac19-e40ffa137f29.png)



![Image](https://user-images.githubusercontent.com/87365901/177107362-d2bc0dfe-892a-4d94-a692-6317a447f1ab.png)



![Image](https://user-images.githubusercontent.com/87365901/177107391-ae1371b3-91ee-40a1-bb36-b8bf46f33200.png)



![Image](https://user-images.githubusercontent.com/87365901/177107442-52ffa36d-92b2-4588-a7de-c849b2b774a0.png)

**Comment by roienatan** [comment]
@DeerstalkerHats are you sure you want to have the input box in that size? for me it looks weird as the address will never be in that length 
<img width="634" alt="Screen Shot 2022-08-10 at 10 29 53" src="https://user-images.githubusercontent.com/34843014/183797259-47989891-3a31-4ef8-96b5-355a5a391537.png">
