### ISSUE TITLE
CTF#2 Countdown, New tutorial

### ISSUE THREAD

**Issue by DeerstalkerHats** [hats-finance/hats#340]
New features for CTF#2

1. Countdown
Countdown to start 
![image](https://user-images.githubusercontent.com/87365901/191313517-106db099-f906-4d40-9a93-db104e25ee2d.png)

When open to submissions
![image](https://user-images.githubusercontent.com/87365901/191313806-f06f6107-1e54-43e4-a41c-b68fa7dd44f0.png)

Ended
![image](https://user-images.githubusercontent.com/87365901/191313884-70d89bd2-e105-4ae1-960c-f96905d11bf9.png)

See the design in Figma https://www.figma.com/file/XkYFhYf9eVDlaX6oL3COf2/Hats-hand-over?node-id=9541%3A8417

2. New tutorial
On submission page 
![image](https://user-images.githubusercontent.com/87365901/191315112-3d45e8a7-b73b-4ab3-b2b5-0ff728d3529b.png)
When clicking view btn the vid will open
![image](https://user-images.githubusercontent.com/87365901/191315414-3a71eb1a-2ca0-42f9-91cc-85b14a328d4d.png)

Vid link https://drive.google.com/drive/folders/10MRH775i3VuDdm_Oaao_5kwIyCwKDIqh?usp=sharing

**Comment by leviyehonatan** [comment]
https://hats-finance.mypinata.cloud/ipfs/Qmf4mFM9uLkBHST7NbdTCPD25vKpbuzf36qLsHtcnqqGCb
