### ISSUE TITLE
Vault Editor 

### ISSUE THREAD

**Issue by leviyehonatan** [hats-finance/hats#90]
Allow creating editing a new vault data object called IVaultDescription in the project

some of the features:
access to the vault editor is only allowed by creating a special link to prevent abuse of the service which provides ipfs pinning
Allow pinng an edited vault to ipfs including images used
Helpers: Profile Images taken automatically
allow to collect due diligence related to the vault

**Comment by roienatan** [comment]
Solved in https://github.com/hats-finance/hats/pull/114
